# Klasy występujące w bazie

age,sex,bmi,children,smoker,region,expenses

In [66]:
import pandas as pd

df = pd.read_csv('med-expense.csv')
df['region']

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...    
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: object

In [67]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [68]:
["fname", "height", "lname", "weight", "today_date", "kids", "sex", "smoking", "age", "race"]

['fname',
 'height',
 'lname',
 'weight',
 'today_date',
 'kids',
 'sex',
 'smoking',
 'age',
 'race']

In [69]:
df

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [70]:
for index, row in df.iterrows():
    df.iloc[index, 1] = int(row.iloc[1] == "male")
    df.iloc[index, 4] = int(row.iloc[4] == "yes")

print(df)

      age sex   bmi  children smoker     region  expenses
0      19   0  27.9         0      1  southwest  16884.92
1      18   1  33.8         1      0  southeast   1725.55
2      28   1  33.0         3      0  southeast   4449.46
3      33   1  22.7         0      0  northwest  21984.47
4      32   1  28.9         0      0  northwest   3866.86
...   ...  ..   ...       ...    ...        ...       ...
1333   50   1  31.0         3      0  northwest  10600.55
1334   18   0  31.9         0      0  northeast   2205.98
1335   18   0  36.9         0      0  southeast   1629.83
1336   21   0  25.8         0      0  southwest   2007.95
1337   61   0  29.1         0      1  northwest  29141.36

[1338 rows x 7 columns]


In [71]:
from sklearn.preprocessing import OneHotEncoder

model_enc = OneHotEncoder()
model_enc = model_enc.fit(df.iloc[:,5:6])
print(model_enc.categories_)
model_enc = model_enc.transform(df.iloc[:,5:6])
model_enc_arr = model_enc.toarray()
print(model_enc_arr[-6:])


[array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [72]:
df.drop(columns='region', inplace=True)

In [73]:

df = df.join(pd.DataFrame(
    {
        'is_southwest': model_enc_arr[:,3],
        'is_southeast': model_enc_arr[:,2],
        'is_northwest': model_enc_arr[:,1],
        'is_northeast': model_enc_arr[:,0]
    }, index=df.index
))

In [74]:
df

age sex   bmi  children smoker  expenses  is_southwest  is_southeast  \
0      19   0  27.9         0      1  16884.92           1.0           0.0   
1      18   1  33.8         1      0   1725.55           0.0           1.0   
2      28   1  33.0         3      0   4449.46           0.0           1.0   
3      33   1  22.7         0      0  21984.47           0.0           0.0   
4      32   1  28.9         0      0   3866.86           0.0           0.0   
...   ...  ..   ...       ...    ...       ...           ...           ...   
1333   50   1  31.0         3      0  10600.55           0.0           0.0   
1334   18   0  31.9         0      0   2205.98           0.0           0.0   
1335   18   0  36.9         0      0   1629.83           0.0           1.0   
1336   21   0  25.8         0      0   2007.95           1.0           0.0   
1337   61   0  29.1         0      1  29141.36           0.0           0.0   

      is_northwest  is_northeast  
0              0.0           0.0  
1              0.0           0.0  
2              0.0           0.0  
3              1.0           0.0  
4              1.0           0.0  
...            ...           ...  
1333           1.0           0.0  
1334           0.0           1.0  
1335           0.0           0.0  
1336           0.0           0.0  
1337           1.0           0.0  

[1338 rows x 10 columns]

In [75]:
df.rename(columns = {'sex':'is_man', 'smoker':'is_smoking'}, inplace = True)
cols = df.columns.tolist()
cols = cols[:5] + cols[6:] + cols[5:6]
df = df[cols]
df

age is_man   bmi  children is_smoking  is_southwest  is_southeast  \
0      19      0  27.9         0          1           1.0           0.0   
1      18      1  33.8         1          0           0.0           1.0   
2      28      1  33.0         3          0           0.0           1.0   
3      33      1  22.7         0          0           0.0           0.0   
4      32      1  28.9         0          0           0.0           0.0   
...   ...    ...   ...       ...        ...           ...           ...   
1333   50      1  31.0         3          0           0.0           0.0   
1334   18      0  31.9         0          0           0.0           0.0   
1335   18      0  36.9         0          0           0.0           1.0   
1336   21      0  25.8         0          0           1.0           0.0   
1337   61      0  29.1         0          1           0.0           0.0   

      is_northwest  is_northeast  expenses  
0              0.0           0.0  16884.92  
1              0.0           0.0   1725.55  
2              0.0           0.0   4449.46  
3              1.0           0.0  21984.47  
4              1.0           0.0   3866.86  
...            ...           ...       ...  
1333           1.0           0.0  10600.55  
1334           0.0           1.0   2205.98  
1335           0.0           0.0   1629.83  
1336           0.0           0.0   2007.95  
1337           1.0           0.0  29141.36  

[1338 rows x 10 columns]

In [78]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

x

age is_man   bmi  children is_smoking  is_southwest  is_southeast  \
0      19      0  27.9         0          1           1.0           0.0   
1      18      1  33.8         1          0           0.0           1.0   
2      28      1  33.0         3          0           0.0           1.0   
3      33      1  22.7         0          0           0.0           0.0   
4      32      1  28.9         0          0           0.0           0.0   
...   ...    ...   ...       ...        ...           ...           ...   
1333   50      1  31.0         3          0           0.0           0.0   
1334   18      0  31.9         0          0           0.0           0.0   
1335   18      0  36.9         0          0           0.0           1.0   
1336   21      0  25.8         0          0           1.0           0.0   
1337   61      0  29.1         0          1           0.0           0.0   

      is_northwest  is_northeast  
0              0.0           0.0  
1              0.0           0.0  
2              0.0           0.0  
3              1.0           0.0  
4              1.0           0.0  
...            ...           ...  
1333           1.0           0.0  
1334           0.0           1.0  
1335           0.0           0.0  
1336           0.0           0.0  
1337           1.0           0.0  

[1338 rows x 9 columns]

In [79]:
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...   
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [95]:
x = x.to_numpy()
x

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [96]:
y = y.to_numpy()
y

array([16884.92,  1725.55,  4449.46, ...,  1629.83,  2007.95, 29141.36])

In [97]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [99]:
# model.predict(x.iloc[0:1,:])
model.predict(x[0:1,:])

array([25292.73983296])

In [100]:
y_pred = model.predict(x)

In [101]:
from sklearn.metrics import mean_squared_error as MSE

MSE(y, y_pred)

36499631.63514606

In [102]:
from joblib import dump, load
dump(model, 'model.joblib') 

['model.joblib']